[workspace]
resolver = "2"
members = ["crates/*", ]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/velyst"
readme = "README.md"

[workspace.dependencies]
# Bevy dependencies
bevy = { version = "0.14.1", default-features = false }
bevy_vello = "0.6.1"
vello = "0.2.1"
vello_svg = "0.3.1"
# Typst dependencies
typst = { git = "https://github.com/typst/typst", rev = "8501a655" }
typst-assets = { version = "0.11", features = ["fonts"] }
comemo = "0.4" # in sync with typst
unicode-math-class = "0.1" # in sync with typst
# Common dependencies
ecow = { version = "0.2", features = ["serde"] }
thiserror = "1"

[workspace.lints.clippy]
redundant_type_annotations = "warn"
bool_comparison = "allow"

[package]
name = "velyst"
description = "A Typst integration for Vello and Bevy."
exclude = ["/assets/", "/.github/", "/examples/"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
typst_element = { version = "0.1.0", path = "crates/typst_element" }
typst_vello = { version = "0.1.0", path = "crates/typst_vello" }
bevy = { workspace = true }
bevy_vello = { workspace = true }
typst = { workspace = true }
typst-assets = { workspace = true, optional = true }
comemo = { workspace = true }
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std"] }
ecow = { workspace = true }
thiserror = { workspace = true }
velyst_macros = { version = "0.1.0", path = "crates/velyst_macros" }

[features]
default = ["embed-fonts"]
embed-fonts = ["dep:typst-assets"]

[dev-dependencies]
bevy = { version = "0.14.1", features = ["file_watcher"] }

[lints]
workspace = true
